### PR TITLE
Solving circular import hack

### LINKED ISSUE #443: Cannot find module nlp
**rrule version**: 2.6.6
**OS**: OSX
**$ date**:  Sun Dec 13 19:40:34 PST 2020

## Output

Not sure why this imports are unhappy here. This is from the console in an Electron app:

```
internal/modules/cjs/loader.js:798 Uncaught (in promise) Error: Cannot find module './nlp'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (internal/modules/cjs/loader.js:798)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (reset-search-paths.ts:40)
    at Module._load (internal/modules/cjs/loader.js:691)
    at Module._load (electron/js2c/asar.js:717)
    at Function.Module._load (electron/js2c/asar.js:717)
    at Module.require (internal/modules/cjs/loader.js:853)
    at require (internal/modules/cjs/helpers.js:74)
    at w (app.js:1)
    at s (app.js:1)
    at getnlp (eval at <anonymous> (app.js:1), <anonymous>:14790:23)
```

## Code

The error occurs when I call this (TypeScript):

```
import RRule from 'rrule';
// also tried
// import RRule from 'rrule/dist/esm/src/rrule';

...

const schedule = RRule.fromText("Every Sunday");
```

## Build

Typescript with rollup.

rollup.config.js

```
import typescript from '@rollup/plugin-typescript';
import {nodeResolve} from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';

export default {
  input: 'src/main.ts',
  output: {
    dir: '.',
    sourcemap: 'inline',
    format: 'cjs',
    exports: 'default'
  },
  external: ['obsidian'],
  plugins: [
    typescript(),
    nodeResolve({browser: true}),
    commonjs(),
  ],
};
```

### PR DESCRIPTION
**Pull request by olemartinorg**
These fixes should prevent problems with circular imports. I still get 14 warnings about circular imports in rollup (regardless of using the main commonjs plugin or the alternate one), but at least the emitted code seems to work fine in both now.

This fixes #443 and hopefully #430, although I haven't been able to reproduce the issue in webpack.

I also looked into extracting other circular usages (like `totext.ts` accessing `RRule.FREQUENCIES`), but that quickly produced quite a lot of changes. I can continue trying to weed out the rest of the circular import warnings if you want, just let me know. 

---

### Thanks for contributing to `rrule`!

To submit a pull request, please verify that you have done the following:

- [Y] Merged in or rebased on the latest `master` commit
- [Y] Linked to an existing bug or issue describing the bug or feature you're
      addressing
- [N] Written one or more tests showing that your change works as advertised

### CODE REVIEW

**Comment by tgrosinger** [comment]
I can confirm that it solves #443 for me.

**Comment by kibertoad** [comment]
@jakubroztocil Ping?..

**Comment by tgrosinger** [comment]
Any chance we can get this merged? It's difficult using an unpublished fork in my project.

@jakubroztocil or @olemartinorg?

**Comment by olemartinorg** [comment]
I would if I could. As for me, I don't really care that much anymore. I have stopped using the dependency that had this as a dependency in my project - so don't count on me for solving the other circular import problems.

**Comment by kibertoad** [comment]
I would be more than happy to help address remaining circular dependencies, as well as help maintaining project in general (we plan to start depending on it from `node-schedule`), but looks like current maintainers are MIA :(

**Comment by tgrosinger** [comment]
In the interim I [published a package](https://www.npmjs.com/package/@tgrosinger/rrule) with this change so I can use it in my project easier

**Comment by tgrosinger** [comment]
> I would if I could. As for me, I don't really care that much anymore. I have stopped using the dependency that had this as a dependency in my project - so don't count on me for solving the other circular import problems.

That's totally fair. Thanks again @olemartinorg for the work you did to get it to this point. It's been hugely helpful.

**Comment by shawndoyle** [comment]
I've been trying to solve this all day!  I hope this gets merged soon!  Thanks @olemartinorg !

File: src/rrule.ts [hunk 1]
```diff
@@ -13,19 +13,6 @@ import { Cache, CacheKeys } from './cache'
...
-  (): Nlp
-}
-
-const getnlp: GetNlp = function () {
-  // Lazy, runtime import to avoid circular refs.
-  if (!getnlp._nlp) {
-    getnlp._nlp = require('./nlp')
-  }
-  return getnlp._nlp
-} as GetNlp
```
Comment (davidgoli) [inline src/rrule.ts:27]: The rationale for this IIRC was to make `nlp` an optional dependency - I had in mind to eventually split it out into its own package. But this simplifies things for now, so we should merge it.

File: src/nlp/index.ts [hunk 2]
```diff
@@ -108,12 +109,12 @@ const common = [
...
-ToText.IMPLEMENTED[RRule.DAILY] = ['byhour'].concat(common)
-ToText.IMPLEMENTED[RRule.WEEKLY] = common
-ToText.IMPLEMENTED[RRule.MONTHLY] = common
-ToText.IMPLEMENTED[RRule.YEARLY] = ['byweekno', 'byyearday'].concat(common)
+ToText.IMPLEMENTED[Frequency.HOURLY] = common
+ToText.IMPLEMENTED[Frequency.MINUTELY] = common
+ToText.IMPLEMENTED[Frequency.DAILY] = ['byhour'].concat(common)
+ToText.IMPLEMENTED[Frequency.WEEKLY] = common
+ToText.IMPLEMENTED[Frequency.MONTHLY] = common
+ToText.IMPLEMENTED[Frequency.YEARLY] = ['byweekno', 'byyearday'].concat(common)
```
Comment (davidgoli) [inline src/nlp/index.ts:117]: 👍

**Review by davidgoli — APPROVED** [review]

**Comment by tgrosinger** [comment]
Hooray, thank you!

**Comment by shawndoyle** [comment]
Amazing!!!

**Comment by tgrosinger** [comment]
@davidgoli would you also be able to publish a new release to NPM? I don't think I can use the changes in my project until a release has been made.

**Comment by davidgoli** [comment]
Published 2.6.8
