### PR TITLE
Fix .d.ts type output

### LINKED ISSUE #263: Bad compilation
**Versions**
```
angular        6.1.1
rrule          2.3.6
```

**Bug**
When I serve/build my application I have this bug
```
ERROR in node_modules/rrule/dist/esm/rrule.d.ts(32,25): error TS2307: Cannot find module 'src/weekday'.
node_modules/rrule/dist/esm/rrule.d.ts(33,25): error TS2307: Cannot find module 'src/weekday'.
node_modules/rrule/dist/esm/rrule.d.ts(34,25): error TS2307: Cannot find module 'src/weekday'.
node_modules/rrule/dist/esm/rrule.d.ts(35,25): error TS2307: Cannot find module 'src/weekday'.
node_modules/rrule/dist/esm/rrule.d.ts(36,25): error TS2307: Cannot find module 'src/weekday'.
node_modules/rrule/dist/esm/rrule.d.ts(37,25): error TS2307: Cannot find module 'src/weekday'.
node_modules/rrule/dist/esm/rrule.d.ts(38,25): error TS2307: Cannot find module 'src/weekday'.
```

**Problem (I guess)**
I went to the `rrule.d.ts` file and I saw this int it : 
```
...
static readonly MO: import("src/weekday").default;
static readonly TU: import("src/weekday").default;
static readonly WE: import("src/weekday").default;
static readonly TH: import("src/weekday").default;
static readonly FR: import("src/weekday").default;
static readonly SA: import("src/weekday").default;
static readonly SU: import("src/weekday").default;
...
```

The problem here is that the import refers to the src and it should not.

I must downgrade to the `2.3.4` which seems to works.

### PR DESCRIPTION
**Pull request by davidgoli**
Fixes #263. Also adds a build step to verify the compiled .d.ts files in `dist/` which would've caught this, and would now abort the commit if .d.ts output has errors. (Ideally Typescript wouldn't output syntax errors to begin with, but this is better than nothing.)

---

### Thanks for contributing to `rrule`!

To submit a pull request, please verify that you have done the following:

- [x] Merged in or rebased on the latest `master` commit
- [x] Linked to an existing bug or issue describing the bug or feature you're
      addressing
- [x] Written one or more tests showing that your change works as advertised
- [x] Run `yarn build` to rebuild the `dist/` files

### CODE REVIEW

File: src/rrule.ts [hunk 1]
```diff
@@ -41,6 +31,16 @@ const getnlp: GetNlp = function () {
...
 
+export const Days = {
+  MO: new Weekday(0),
+  TU: new Weekday(1),
+  WE: new Weekday(2),
+  TH: new Weekday(3),
+  FR: new Weekday(4),
+  SA: new Weekday(5),
+  SU: new Weekday(6)
+}
```
Comment (davidgoli) [inline src/rrule.ts]: Lemme just say for the record I don't love the fact that these enums are duplicated onto the RRule class eg. `RRule.MO, RRule.TU` etc, also `Frequency`. But it would be a breaking change to remove them. Probably a big API overhaul is coming for 3.0.
